In [2]:
import urllib.request
import numpy as np

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x26fd061ee30>)

In [ ]:
climate_data = np.genfromtxt('climate.txt', delimiter = ',', skip_header=1)

In [6]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [7]:
climate_data.shape

(10000, 3)

In [8]:
#now we can perform matrix multiplication using the @ operator to predict the yield of apples for the entire dataset 
#using a given set of weights

weights =np.array([0.3,0.2,0.5])

In [9]:
yields = climate_data @ weights

In [10]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [11]:
yields.shape
#will return the dimensions of the yield array

(10000,)

In [13]:
#now we'll add the yields as a fourth column to the climate_data using the np.concatenate function
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [14]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])