In [12]:
w1, w2, w3 = 0.3, 0.2, 0.5


In [13]:
kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]

In [14]:
weights = [w1,w2,w3]

In [15]:
def crop_yield(region,weights):
    result=0
    for x,w in zip(region,weights):
        result += x*w
    return result

In [16]:
crop_yield(kanto,weights)


56.8

In [1]:
%pip install numpy --upgrade --quiet

Note: you may need to restart the kernel to use updated packages.


In [18]:
import numpy as np

In [19]:
kanto = np.array([73,67,43])

In [20]:
kanto

array([73, 67, 43])

In [21]:
weights = np.array([w1,w2,w3])

In [22]:
weights

array([0.3, 0.2, 0.5])

In [23]:
type(kanto)

numpy.ndarray

In [24]:
type(weights)

numpy.ndarray

In [25]:
#for finding the dot product of the following
np.dot(kanto,weights)
#dot product is achieved by the concept of vectorisation

56.8

In [26]:
(kanto*weights).sum()

56.8

In [27]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [28]:
arr1*arr2

array([ 4, 10, 18])

In [29]:
arr2.sum()

15

In [30]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

arr1_np = np.array(arr1)
arr2_np = np.array(arr2)


In [31]:
%%time
result =0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

CPU times: total: 156 ms
Wall time: 170 ms


833332333333500000

In [32]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 3.01 ms


-1942957984

In [33]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [34]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [35]:
climate_data.shape

(5, 3)

In [36]:
weights

array([0.3, 0.2, 0.5])

In [37]:
weights.shape

(3,)