In [1]:
import numpy as np

a =np.random.randn(5)

In [2]:
print(a)

[-0.5838933   0.8686565   0.39471133  0.11569209  0.40295522]


In [3]:
a.shape

(5,)

In [4]:
print(a.T)

[-0.5838933   0.8686565   0.39471133  0.11569209  0.40295522]


In [5]:
print(np.dot(a,a.T))

1.4270500968261535


In [6]:
a= np.random.randn(5,1)
print(a)

[[-1.18752254]
 [-1.02253979]
 [-1.70089787]
 [ 0.11692874]
 [ 0.19964541]]


In [7]:
print(a.T)

[[-1.18752254 -1.02253979 -1.70089787  0.11692874  0.19964541]]


In [8]:
print(np.dot(a,a.T))

[[ 1.41020978  1.21428904  2.01985456 -0.13885552 -0.23708343]
 [ 1.21428904  1.04558762  1.73923575 -0.11956429 -0.20414538]
 [ 2.01985456  1.73923575  2.89305358 -0.19888385 -0.33957646]
 [-0.13885552 -0.11956429 -0.19888385  0.01367233  0.02334429]
 [-0.23708343 -0.20414538 -0.33957646  0.02334429  0.03985829]]
